c Warning: do not edit this file, it has possibly been generated by configure
c TELESCOPE=sma
c=======================================================================
	CHARACTER*(*) MIRTEL
	PARAMETER(MIRTEL='sma')
	INTEGER   MAXBUF
	PARAMETER(MAXBUF=10000000)
c
	INTEGER   MAXDIM, MAXDIM2
	PARAMETER(MAXDIM=4096,MAXDIM2=8192)
c
	INTEGER   MAXIANT,MAXANT,MAXANT2
	PARAMETER(MAXIANT=256,MAXANT=30,MAXANT2=28)
c		maximum number of baselines
	INTEGER   MAXBASE
c	PARAMETER(MAXBASE=((MAXANT*(MAXANT+1))/2))
	PARAMETER(MAXBASE=435)
	INTEGER   MAXBASE2
	PARAMETER(MAXBASE2=1058)
c
	INTEGER   MAXCHAN
	PARAMETER(MAXCHAN=12288)
c
	INTEGER   MAXWIN
	PARAMETER(MAXWIN=48)
c
	INTEGER   MAXWIDE
	PARAMETER(MAXWIDE=50)
c=======================================================================

